/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthAuthViewRouteImport } from './routes/auth/$authView'
import { Route as AppReposRouteImport } from './routes/_app/repos'
import { Route as AppContributionsRouteImport } from './routes/_app/contributions'
import { Route as AppApiKeysRouteImport } from './routes/_app/api-keys'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReposRoute = AppReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContributionsRoute = AppContributionsRouteImport.update({
  id: '/contributions',
  path: '/contributions',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/api-keys': typeof AppApiKeysRoute
  '/contributions': typeof AppContributionsRoute
  '/repos': typeof AppReposRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesByTo {
  '/api-keys': typeof AppApiKeysRoute
  '/contributions': typeof AppContributionsRoute
  '/repos': typeof AppReposRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/api-keys': typeof AppApiKeysRoute
  '/_app/contributions': typeof AppContributionsRoute
  '/_app/repos': typeof AppReposRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-keys'
    | '/contributions'
    | '/repos'
    | '/auth/$authView'
    | '/api/auth/$'
    | '/api/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api-keys'
    | '/contributions'
    | '/repos'
    | '/auth/$authView'
    | '/'
    | '/api/auth/$'
    | '/api/v1/$'
  id:
    | '__root__'
    | '/_app'
    | '/_app/api-keys'
    | '/_app/contributions'
    | '/_app/repos'
    | '/auth/$authView'
    | '/_app/'
    | '/api/auth/$'
    | '/api/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthAuthViewRoute: typeof AuthAuthViewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/repos': {
      id: '/_app/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof AppReposRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contributions': {
      id: '/_app/contributions'
      path: '/contributions'
      fullPath: '/contributions'
      preLoaderRoute: typeof AppContributionsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/api-keys': {
      id: '/_app/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppContributionsRoute: typeof AppContributionsRoute
  AppReposRoute: typeof AppReposRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppApiKeysRoute: AppApiKeysRoute,
  AppContributionsRoute: AppContributionsRoute,
  AppReposRoute: AppReposRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthAuthViewRoute: AuthAuthViewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
